apiVersion: apps/v1
kind: Deployment
metadata:
  name: dootask-office
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dootask-office
  template:
    metadata:
      labels:
        app: dootask-office
    spec:

      containers:
      - name: office
        image: onlyoffice/documentserver:9.2.0
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: dootask-secret
              key: APP_KEY
        volumeMounts:
        - name: logs
          mountPath: /var/log/onlyoffice
        
      - name: office-logs
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - |
          tail -F /var/log/onlyoffice/*.log 2>/dev/null || true
        volumeMounts:
        - name: logs
          mountPath: /var/log/onlyoffice
      volumes:
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: dootask-office
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: dootask-office
---
