apiVersion: apps/v1
kind: Deployment
metadata:
  name: dootask-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dootask-ai
  template:
    metadata:
      labels:
        app: dootask-ai
    spec:
      containers:
      - name: ai
        image: kuaifan/dootask-ai:0.4.1
        env:
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: dootask-secret
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: dootask-secret
              key: REDIS_PORT

